import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer2 } from "@/components/footer2";

// import { TutorCard } from "./components/tutors/TutorCard";
import { HelpCenter } from "@/components/help1";

import { Toaster } from "sonner";
import Navbar1 from "@/components/navbar1";
import HeroSection from "@/components/HeroSection";

import EventCategories from "@/app/components/sections/EventCategories";
import UpcomingEventsSlider from "@/components/UpcomingEventsSlider";
import CallToActionSection from "./components/call/CallToActionSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Planora 📅",
  // description: "Generated by create next app",
  description: "Smart Event Management",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar1></Navbar1>
        
        {children}
        <Toaster richColors></Toaster>

        <HeroSection></HeroSection>

        {/* <TutorCard></TutorCard> */}

        <UpcomingEventsSlider></UpcomingEventsSlider>

        <EventCategories></EventCategories>

        <CallToActionSection></CallToActionSection>

        <HelpCenter></HelpCenter>

        <Footer2></Footer2>
      </body>
    </html>
  );
}
